### ISSUE TITLE
"Search Everywhere" will stop returning file search results if all editor tabs are closed

### ISSUE THREAD

**Issue by esplace** [dinhhuy258/tab-number#1]
### Description

The plugin breaks file search in "Search Everywhere" if all editor tabs are closed

### Steps to reproduce

1. Enable the plugin
2. Close all editor tabs
3. Search for any file that exists in a project (`Ctrl+Shift+N`)

Expected Result: IDE shows search results
Actual Result: search does not return any results. An exception occurs in the plugin

### Other information

Reproducible using Intellij IDEA 2021.1.3 and Tab Number 1.0.0

https://user-images.githubusercontent.com/67322870/126651979-9ce51c5a-5077-4b7b-9ded-53854d5f1007.mp4

**Comment by esplace** [comment]
Stack trace:
```
java.lang.IllegalStateException: fileEditorManagerEx.currentWindow must not be null
	at com.dinhhuy258.tabnumber.providers.TabNumberEditorTabTitleProvider.getEditorTabTitle(TabNumberEditorTabTitleProvider.kt:17)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitle(EditorTabTitleProvider.java:24)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:21)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.lambda$getPresentableNameForUI$0(VfsPresentationUtil.java:29)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getPresentableNameForUI(VfsPresentationUtil.java:29)
	at com.intellij.ide.actions.SearchEverywherePsiRenderer.getElementText(SearchEverywherePsiRenderer.java:82)
	at com.intellij.ide.util.PsiElementListCellRenderer$LeftRenderer.customizeCellRenderer(PsiElementListCellRenderer.java:135)
	at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:47)
	at com.intellij.ide.util.PsiElementListCellRenderer.lambda$getListCellRendererComponent$1(PsiElementListCellRenderer.java:231)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.ide.util.PsiElementListCellRenderer.getListCellRendererComponent(PsiElementListCellRenderer.java:230)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.lambda$getListCellRendererComponent$0(MixedListFactory.java:79)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.getListCellRendererComponent(MixedListFactory.java:78)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:197)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:325)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:301)
	at com.intellij.ui.components.WideSelectionListUI.paint(WideSelectionListUI.java:34)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:800)
	at com.intellij.ui.components.JBList.paintComponent(JBList.java:174)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at com.intellij.ui.components.JBList.paint(JBList.java:106)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5263)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5211)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5021)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by dinhhuy258** [comment]
Thanks for reporting the bug. I already fixed it. 
You can download the latest version in the `Release` section in GitHub and install the patch manually, or you can wait for the patch to be released on the Intellij Marketplace.
